name: Java CI with Maven

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ITBlogs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: "17"
          cache: "maven"
      - name: Build with Maven
        run: mvn -B package --file pom.xml
