name: Node.js CI

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    defaults:
      run:
        working-directory: ITBlogs-Client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ITBlogs-Client/package-lock.json
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: npm clean install
        run: npm ci
      - name: npm run build
        run: npm run build --if-present
